SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ENTIDADE](
	[ENTIDADE] [int] NOT NULL,
	[NOMECOMPLETO] [varchar](100) NOT NULL,
	[SITUACAO] [smallint] NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[ORIGEM] [varchar](10) NULL,
	[FACE] [varchar](5000) NULL,
 CONSTRAINT [PK_ENTIDADE_ENTIDADE] PRIMARY KEY CLUSTERED 
(
	[ENTIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[IMAGEMENTIDADE] DROP CONSTRAINT [FK_IMAGEMENTIDADE_ENTIDADE]
GO


/****** Object:  Table [dbo].[IMAGEMENTIDADE]    Script Date: 20/04/2019 18:27:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IMAGEMENTIDADE](
	[IMAGEMENTIDADE] [int] NOT NULL,
	[ENTIDADE] [int] NULL,
	[SITUACAO] [smallint] NULL,
	[DTCADASTRO] [datetime] NULL,
	[FACE] [text] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[IMAGEMENTIDADE]  WITH CHECK ADD  CONSTRAINT [FK_IMAGEMENTIDADE_ENTIDADE] FOREIGN KEY([ENTIDADE])
REFERENCES [dbo].[ENTIDADE] ([ENTIDADE])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[IMAGEMENTIDADE] CHECK CONSTRAINT [FK_IMAGEMENTIDADE_ENTIDADE]
GO


