CREATE TABLE "FABRICANTE" (
	"FABRICANTE"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"DESCRICAO"	VARCHAR(50) NOT NULL UNIQUE,
	"REVISAO"	INTEGER
)

CREATE TABLE "MODELO" (
	"MODELO"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"DESCRICAO"	VARCHAR(50) NOT NULL,
	"FABRICANTE"	INTEGER,
	"REVISAO"	INTEGER,
	FOREIGN KEY (FABRICANTE) REFERENCES FABRICANTE(FABRICANTE)
	
)

CREATE TABLE "EQUIPAMENTO" (
	"EQUIPAMENTO"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"MODELO"	INTEGER,
	"DESCRICAO"	VARCHAR(50) UNIQUE,
	"REVISAO"	INTEGER,
	"SERIE"	VARCHAR(30),
	"CATEGORIA"	VARCHAR(30),
	"DTENTRADA"	TIMESTAMP NOT NULL,
	"DTSAIDA"	TIMESTAMP,
	FOREIGN KEY("MODELO") REFERENCES "MODELO"("MODELO")
)